# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - windows
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5

notifications:
  email: false